#docker-compose.yml 
#docker-compose up -d --build

version: '3'
services:
  postgres:
        build: ./postgres
        ports:
            - 5432:5432
  springboot:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    depends_on:
        - postgres

