server:
  port: 8080

spring:
  datasource:
    platform: Postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/logging
    username: postgres
    password: postgrespw
    hikari:
      connection-timeout: 15000
      maximum-pool-size: 3
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgresSQLDialect

logging:
  level:
    ROOT: info